### PR TITLE
Added new organization source from github

### LINKED ISSUE #2: Add new images origin
Now we have a new organization to store images called https://github.com/azuki-images but the images.azk.io is not configured to load images from it.

### PR DESCRIPTION
**Pull request by quintanilhar**
This PR aims to closes #2 issue, I added new organization source from github and change every azukiapp hardcoded namespace.

### CODE REVIEW

**Comment by gullitmiranda** [comment]
LGTM

**Comment by nuxlli** [comment]
LGTM

**Comment by marcusgadbem** [comment]
Hi @quintanilhar! Thanks for your contribution.

I've made a small mistake by forgetting to merge back the last updates on images.azk.io made on  `refactor_workflow` branch and I apologize for that. However your PR still makes perfect sense.
I will merge your PR, rebase the branchs and make some tests.

For now I have 2 considerations about it:
- We really liked the idea to support multiple organizations but one the thing that came to our attention is the new URL structure. Currently it works as `http://images.azk.io/#/[repo]` and defaults organization to `azukiapp`. Your PR proposes it to work as `http://images.azk.io/#/[org]/[repo]`. Do you have any suggestions on how to tackle this in order to avoid external broken links?
- When I change the `namespace`, the left sidebar keeps loading repositories from `azukiapp`. Can I add this enhacement or you can do that? :)

**Comment by quintanilhar** [comment]
Hi @marcusgadbem!

No problem for that, about possible broken links, I think that it is pretty good to create a redirect 301 to the new one and fix the org for a while.
For the second consideration, did you say that the namespace could be a filter to the left sidebar? I thought that it was the "main" menu, I suppose that it is better to show the namespace and leave all the images there.

What do you think about it? I can do this if you want :D

Ps.: Sorry for my delay :)

**Comment by marcusgadbem** [comment]
I agree that redirect 301 would be the best solution but because of our url model (`#`) we are not able to treat it on a back-end level (also, it is deployed on AmazonS3). 
I guess we will have to stick with a hack (middleware) on top of the router that validates the amount of parameters. What do you think about it?

About the left sidebar (main menu), currently it builds itself by searching for all repositories under `azukiapp` which prefixes with `docker-`. By changing the `namespace`, I think the main menu should point the search to the provided `namespace`. That would facilitate users to navigate through the organization images without having to take a look on the organization at GitHub.

Would be great if you could make these modifications. :)

**Comment by quintanilhar** [comment]
I did the old link compatibility and I think that we could implement the org filter in a different issue, what you think?

**Comment by gullitmiranda** [comment]
We intend to have multiple organizations?. it is worth remembering the following: 
1. all the images in https://github.com/azukiapp will be transferred to https://github.com/azuki-images gradually. 
2. in Docker Hub, all images are just an organization (`azukiapp`).

Now one thing that would be important is a search engine (filter by name), after all, the number of images should increase.

> my 5c$

**Comment by marcusgadbem** [comment]
@quintanilhar Cool, man! :)  LGTM :+1: 
I think the org filter can also be added on this issue/pr if you don't mind. These updates are closely related.
Sorry I also realized (hope in time) we need to take care about the right sidebar, the `GitHub Repository` link as well: https://github.com/azukiapp/images.azk.io/blob/master/src%2Fassets%2Fjs%2Fapp.projects.jsx#L235 
Could you also take this? :)

**Comment by marcusgadbem** [comment]
@gullitmiranda we do not intend to have multiple organizations but to support this (gradual) transition and to avoid broken links. I also think this kind of feature (support _different_, not _mutiple_) organization is a good one.  Are we missing something? 

And about the search engine I agree that is a good suggestion and it worth an issue. Would you? :)

**Comment by gullitmiranda** [comment]
yes the linking must be resolved in this PR, which I was talking is about the name that is displayed (https://github.com/azukiapp/images.azk.io/blob/master/src/assets/js/app.jsx#L85)

**Pull request closed without merging**
